Modified the ci/cd pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -15,7 +15,52 @@ env:
   LATEST_TAG: v1
   DVC_DATA_DIR: ./data
 
+# jobs:
+# Hello team ,just mimicing a scenario, will remove the unit test from here later.
+
 jobs:
+  test:
+    name: Unit tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - uses: actions/setup-python@v5
+        name: Setup Python
+        with:
+          python-version: '3.13'
+
+      - name: Install pip
+        run: python -m pip install --upgrade pip
+
+      - name: Check for requirements.txt
+        run: |
+          if [ ! -f ml-pipeline/requirements.txt ]; then
+            echo "requirements.txt not found!"
+            exit 1
+          fi
+
+      - name: Install dependencies
+        run: pip install -r ml-pipeline/requirements.txt
+
+      - name: Test with Pytest
+        run: |
+          set -a
+          source ml-pipeline/.env.example
+          set +a
+          echo "Loaded environment variables:"
+          env | grep POSTGRES_
+          pytest
+
+
+
+
+
+
+
+
+
   # Depends on your existing test workflow - wait for it to succeed
   build-and-push:
     name: Build & push Docker image
@@ -105,6 +150,16 @@ jobs:
           AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
           AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
         run: |
+
+          # Confirm we are in the repo root
+          pwd
+          ls -la
+          
+          # Initialize DVC only if needed
+          if [ ! -d .dvc ]; then
+            dvc init
+          fi
+           
           dvc remote add -d azure_remote azure://telcustomerchurndata/churndata || true
           dvc remote modify --local azure_remote mlchurndatastore $AZURE_STORAGE_ACCOUNT_NAME
           dvc remote modify --local azure_remote account_key $AZURE_STORAGE_ACCOUNT_KE
